name: CI

on:
  push:
    branches:
      - develop

env:
  AWS_REGION: us-east-1
  MAVEN_PROJECTS: kernel,iam-sdk,api,authorizer-funq,process-manager-funq

jobs:

  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetch Unshallow
        run: git fetch --prune --tags --unshallow
      - name: Set JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 21
          cache: maven
          server-id: github
      - name: Install Dependencies
        run: pushd backend && ./mvnw clean install dependency:resolve -am -pl ${MAVEN_PROJECTS} -DskipTests -Djacoco.skip=true -Dpmd.skip=true -Dcpd.skip=true -Dcheckstyle.skip=true && popd

  analyze:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 21
          cache: maven
          server-id: github
          server-username: PACKAGE_ACCESS_USER
          server-password: PACKAGE_ACCESS_TOKEN
      - name: Analyze
        run: pushd backend && mvn clean validate -am -pl ${MAVEN_PROJECTS} -DskipTests -Pcode && popd

  tests:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 21
          cache: maven
          server-id: github
          server-username: PACKAGE_ACCESS_USER
          server-password: PACKAGE_ACCESS_TOKEN
      - name: Tests
        run: pushd backend && mvn clean test -am -pl ${MAVEN_PROJECTS} -Dcpd.skip=true -Dpmd.skip=true -Dcheckstyle.skip=true -Dspotbugs.skip=true && popd
        env:
          CI: true

  build:
    runs-on: ubuntu-latest
    needs:
      - analyze
      - tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 21
          cache: maven
          server-id: github
          server-username: PACKAGE_ACCESS_USER
          server-password: PACKAGE_ACCESS_TOKEN
      - name: Build
        run: pushd backend && ./mvnw verify -am -pl ${MAVEN_PROJECTS} -Dcheckstyle.skip=true -Dspotbugs.skip=true -Dpmd.skip=true -Djacoco.skip=true && popd